apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextjs-graphql-fabianbash-com-prd
spec:
  secretName: nextjs-graphql-fabianbash-com-prd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nextjs-graphql.fabianbrash.com
  dnsNames:
  - nextjs-graphql.fabianbrash.com